### PR TITLE
Add build system and continuous integration (Windows, macOS, Linux)

### PR DESCRIPTION
**Pull request by kevinlul**
Tested on 18.04 Bionic; explanation on wiki
fmt no longer needs to be cloned locally; install via apt-get. Moved in premake5.lua so Windows keeps working for now.
Added .gitignore for premake5 binary since this script drops it right in the working directory for convenience.

### CODE REVIEW

**Comment by DyXel** [comment]
I cannot test this script, and im unwilling to merge without testing. When someone test it we should be able to merge without issues!

**Comment by kevinlul** [comment]
Proof of success: https://travis-ci.org/kevinlul/ygopro/builds/547454936

Can also confirm by testing on [fresh Ubuntu VM image](https://www.osboxes.org/ubuntu/) and following wiki instructions.

TODO: test on fresh WSL again

**Comment by kevinlul** [comment]
At this point, the Linux scripts and CI are working well. I will focus on the remaining platforms and patch the Linux scripts as needed. Platform scripts will be merged into this branch when they are confirmed working well.

**Comment by kevinlul** [comment]
Merged prebuild and deploy system for macOS and updated Travis to match.
- On macOS, Lua installs from source
- Enabled caching `fmt` and `nlohmann-json` on Linux. Caching not enabled for macOS because Lua builds quickly enough
- Do not build `nlohmann-json` and run tests; just download raw from GitHub

Issues:
- only builds on Mojave with Xcode; doesn't build with GCC9 on Mojave either
- *dll configurations don't work

**Comment by kevinlul** [comment]
Polished build system and continuous integration confirmed working on Windows 10 + VS2017, macOS Sierra/High Sierra/Mojave + Xcode Clang, Linux Ubuntu Xenial 16.04 and Bionic 18.04 + GCC5.4/7/9

https://travis-ci.org/kevinlul/ygopro/builds/554317704

**Comment by kevinlul** [comment]
Deploy features added.

**Comment by kevinlul** [comment]
*NB*: remove last "TEMPORARY" commit before merging

**Comment by kevinlul** [comment]
Pending change: revert freetype to system freetype on macOS, test behaviour on Linux and update accordingly.

**Comment by kevinlul** [comment]
Also requires https://github.com/edo9300/ygopro-core/pull/48

**Comment by kevinlul** [comment]
Changes:
- Update gitignore to ignore downloaded prerequisities, dependencies, and deploy directory
- Add scripts in `build-support` to obtain prerequisites, dependencies, build needed dependencies from source, and quickly deploy a usable version. Usage is explained on wiki
  - Obtain most dependencies on Windows from vcpkg, except for freetype (2.6.5) and irrlicht (patched)
  - Build irrlicht (patched) and lua from source on macOS
  - Default Ubuntu scripts are meant for 16.04 Xenial Xerus and 18.04 Bionic Beaver, building missing ones from source. Other distributions and versions will probably need to obtain dependencies manually, following the list on the wiki. (This may be better organized in the future.)
- Add Travis configuration to make use of these build scripts on a cross-platform build matrix, complete with force-push deploying to the specified repository branches
  - These will take longer on first run to build some dependencies from source, but these will be cached
  - Depends on https://github.com/kevinlul/edopro-vcpkg-cache for Windows because Travis takes way too long or times out building from source
- Fix compilation and linking issues on tested platforms and toolchains
- Reorganized build configuration files, removed unneeded ones
- Added premake option to specify image URLs
- Update font to OFL-licensed Noto Sans JP Regular

To do when or after merging:
- Set submodule configuration back to edo9300/ygopro-core
- Update ocgcore pointer appropriately

**Pull request merged**
